################################################################################
# !!!set TOPDIR variable with path to root folder,
#    where ./env is located.
#    set DEPLIBS variable with path to all depended libraries,
#    path from root where ./env is located
#    set SYSLIBS with all necessarily system libraries
# including executable makefile
################################################################################

TOPDIR = ./..

DEPLIBS = multithread

SYSLIBS += pthread
SYSLIBS += rt

include $(TOPDIR)/env/make/exemake
