################################################################################
# !!!set TOPDIR variable which shold describe the path to root folder,
#    where ./env is located.
# including static library makefile
################################################################################

TOPDIR = ./..

include $(TOPDIR)/env/make/libmake
